# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 인생...
subtitle: Hadron Particle Group since 2021.12
email: hjlee6674@gmail.com
description: >-
QCD, Quantum field theory, chiral quark-soliton model
# this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

author_logo: null
author: HwiJae Lee
author_bio: Student who want to be a theoretical physicist
author_email: "hjlee6674@gmail.com"
author_location: Korea
author_website_url: null
typewrite-text: devlopr is a jekyll theme built for developers. You can edit this in _config.yml file


# author_work_experiences:
#             - company_name: Google
#               company_logo: google.png
#               company_url: https://google.com
#               designation: Software Engineer
#               description: Worked on various Google Products
#               visibility: true
#             - company_name: Microsoft
#               company_logo: microsoft.png
#               company_url: https://microsoft.com
#               designation: Azure Developer
#               description: Worked on various Azure Cloud Products
#               visibility: true

# author_education_details:
#               - college_logo: mit.png
#                 college_name: MIT
#                 college_url: https://mit.org
#                 college_degree: CS Engineer
#                 description: Bachelor of Technology
#                 visibility: true

# author_project_details:
#               - project_thumbnail: gamershub.png
#                 project_title: Gamers Hub
#                 project_description: A Platform built for Gamers and Game Devs
#                 project_url: https://gamershub.in
#                 visibility: true
#               - project_thumbnail: hack4r.PNG
#                 project_title: Hack4r
#                 project_description: A Platform built for Hackers and Penetration Testers
#                 project_url: https://hack4r.com
#                 visibility: true

# social links
twitter_username: null
github_username:  sujaykundu777
facebook_username: null
linkedin_username: null
behance_username: null
instagram_username: null
medium_username: null
telegram_username: null
dribbble_username: null
flickr_username: null


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
